// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using Microsoft.VisualStudio.TestTools.UnitTesting;

[TestClass]
public class CreatevoterTest : BaseTest
{
    Steps steps;

    public CreatevoterTest()
    {
    }

    [TestInitialize]
    public override void Initialize()
    {
        base.Initialize();
        steps = new Steps(driver);
        steps.navigate();
    }


    [TestMethod]
    public void CreateVoter()
    {
        steps.create_voter();
    }
}
