// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using Microsoft.VisualStudio.TestTools.UnitTesting;

[TestClass]
public class WhenCreatingGroup : BaseTest
{
    private IWebDriver driver;
    [Test]
    public void createGroup()
    {
        driver.Navigate().GoToUrl("https://localhost:44362/index.html");
        driver.FindElement(By.LinkText("Groups")).Click();
        driver.FindElement(By.CssSelector(".create-button > .v-btn__content")).Click();
        driver.FindElement(By.CssSelector(".group-name")).SendKeys("asdf");
        driver.FindElement(By.CssSelector(".group-description")).SendKeys("asdf");
        driver.FindElement(By.CssSelector(".save-button > .v-btn__content")).Click();
    }
}
